
// This file has been generated by the GUI designer. Do not modify.
namespace osiris
{
	public partial class rango_de_fechas
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget osiris.rango_de_fechas
			this.Name = "osiris.rango_de_fechas";
			this.Title = global::Mono.Unix.Catalog.GetString ("rango_de_fechas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
